### ISSUE TITLE
Next Steps for the project

### ISSUE THREAD

**Issue by MrUnfunny** [casbin/dart-casbin#11]
Hi @hsluoyz and @KNawm,

I am interested in this project for Gsoc but since the barebones are already setup, I'm not sure about how to proceed with this project. Should we start by implementing functional parts such as config file or should we wait for Gsoc period to start? It would be helpful if you can guide on how should we proceed with this project.

Regards

**Comment by hsluoyz** [comment]
@MrUnfunny we should move on making the project work, e.g., for ACL, RBAC, and then ABAC. Have tests to make it pass.
