### ISSUE TITLE
Make the basic ACL & RBAC models work and add some test cases for it

### ISSUE THREAD

**Issue by hsluoyz** [casbin/dart-casbin#13]

**Comment by santhoshivan23** [comment]
@MrUnfunny Lets start working on this?

**Comment by MrUnfunny** [comment]
Sure, how can I contact you?

**Comment by santhoshivan23** [comment]
@MrUnfunny Let's discuss any architecture related approaches for ACL if any?

**Comment by MrUnfunny** [comment]
> @MrUnfunny Let's discuss any architecture related approaches for ACL if any?

Currently I am looking into implementing enforce method to get minimum working prototype. You can tell if you have something specific in your mind. We can also have a meeting at whatever time suits you.

**Comment by MrUnfunny** [comment]
@hsluoyz I think this issue can be closed since we already have tests for ACL and RBAC.

**Comment by hsluoyz** [comment]
@MrUnfunny can you link the PR to this issue?

**Comment by MrUnfunny** [comment]
@hsluoyz [this one](https://github.com/casbin/dart-casbin/pull/22) is for ACL and [this one](https://github.com/casbin/dart-casbin/pull/28) is for RBAC.
