### ISSUE TITLE
Make an example flutter app to show the usage of dart-casbin

### ISSUE THREAD

**Issue by hsluoyz** [casbin/dart-casbin#14]
Can anyone make such an example?

**Comment by MrUnfunny** [comment]
> Can anyone make such an example?

Yes, I'm working on this. Should it be an app with just logon feature and few extra screens to show based on user's roles? Do we have other such examples for other casbin projects which can be used as reference?

**Comment by hsluoyz** [comment]
@MrUnfunny you can refer to the RBAC model in: https://casbin.org/en/editor

1. The app don't need to have backend API. Just local stored data would be OK.
2. alice and bob can log into the app with password 123. And based on their Casbin permissions, they may be able or unable to access data1, data2.
3. (Optional) the app can also set permissions for users, assign bob to access to data too, or show user's roles, etc.

**Comment by MrUnfunny** [comment]
@hsluoyz I created a basic app with login functionality( with dummy data with local data itself) and a screen with 2 data, data1 and data2 in tab view. My idea is that a working version of dart-casbin would be able to show only those data which user is allowed to access. 

https://user-images.githubusercontent.com/43833743/113508291-d3f53080-956c-11eb-9e36-bc6ffc58de32.mp4

Please tell me if you want something different or is this example app fine.

**Comment by hsluoyz** [comment]
@MrUnfunny looks good. First we need to make dart-casbin work.

**Comment by MrUnfunny** [comment]
Yes, I'm working on it too.

**Comment by santhoshivan23** [comment]
@hsluoyz I can work on this in parallel w the ACL model. @MrUnfunny could also help.

**Comment by MrUnfunny** [comment]
Hi @hsluoyz, is the app shown above good enough for our example or do we need to create something else?

**Comment by hsluoyz** [comment]
@MrUnfunny can we download the apk to install?

**Comment by MrUnfunny** [comment]
> 
> 
> @MrUnfunny can we download the apk to install?

yes, we can upload the apk in a folder with example

**Comment by hsluoyz** [comment]
@MrUnfunny can you put the apk into a zip and put it here (this conversation)?

**Comment by MrUnfunny** [comment]
[app-release.zip](https://github.com/casbin/dart-casbin/files/6873983/app-release.zip)

Please take a look.

**Comment by MrUnfunny** [comment]
@hsluoyz did you get the chance to check the apk? If it's good enough we can add it as an example to the package.

**Comment by hsluoyz** [comment]
@MrUnfunny I tried it and it works like a charm! Can you make a PR to upload it to: https://github.com/dart-casbin/dart-casbin-demo-app ?

**Comment by MrUnfunny** [comment]
@hsluoyz just created a PR but generally in dart, we ship demo app with the package itself inside example folder. Should we just add link to the demo app in readme?
