### ISSUE TITLE
Selection of expression evaluator

### ISSUE THREAD

**Issue by ctrysbita** [casbin/dart-casbin#17]
The original golang implementation uses `govaluate` to evaluate expressions in model while node-casbin uses `expression-eval` package. We need to determine a similar way to parse and evaluate expressions in Dart efficiently.

1. Use the [expressions](https://pub.dev/packages/expressions) package which provides similar functions as expression-eval / govaluate. The custom evaluator allows us to handle member expressions manually. But the compatibility has not been fully tested yet. 
2. Use Dart FFI to wrap `govaluate` library under vm runtime and use dart:js to wrap `expression-eval` under JS runtime. This way ensures compatibility with the original golang implementation and may provide higher performance (Go vs Dart). However, using FFI means we have to include an external dynamic library, which may cause an increase in  app size and the complexity of build.

**Comment by hsluoyz** [comment]
@ctrysbita we will choose 1.

**Comment by hsluoyz** [comment]
We will use Dart native library to avoid cross-language RPC problems. This is how we usually do for all languages. An exception is that we may use C/C++ to wrap into a Python wrapper.
