### ISSUE TITLE
release on pub.dev

### ISSUE THREAD

**Issue by MrUnfunny** [casbin/dart-casbin#45]
I think most parts of the project are ready to use. @KNawm @hsluoyz please take a look and if it seems good enough, we can release it on pub.dev

**Comment by hsluoyz** [comment]
@MrUnfunny we already have it: https://pub.dev/packages/casbin

Can we setup semantic-release to make release automatically?

**Comment by MrUnfunny** [comment]
> Can we setup semantic-release to make release automatically?

I'm not sure about this. I'll look into it.

**Comment by MrUnfunny** [comment]
We can set up [semantic-release](https://github.com/semantic-release/semantic-release) for releasing on GitHub but right now there's no semantic-release plugin to publish on [pub.dev](https://pub.dev/). We can try to stitch [flutter-pub-publisher](https://github.com/sakebook/actions-flutter-pub-publisher) with semantic-release to publish on both GitHub and pub.dev but we'll still need to manually change version number in [pubspec.yaml](https://github.com/casbin/dart-casbin/blob/master/pubspec.yaml) and [changelog.md](https://github.com/casbin/dart-casbin/blob/master/CHANGELOG.md). We can also try to create a [plugin](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md) for semantic-release to auto-update pubspec and changelog files.

**Comment by hsluoyz** [comment]
@MrUnfunny can this be used? https://github.com/themizzi/semantic-release-dart

**Comment by MrUnfunny** [comment]
> @MrUnfunny can this be used? https://github.com/themizzi/semantic-release-dart

Looking at it's code, it seems to change pubspec only and not changelog. I'll try to tomowrrow.
