### ISSUE TITLE
Change all functions to follow Golang Casbin's naming convention

### ISSUE THREAD

**Issue by hsluoyz** [casbin/dart-casbin#51]
Such as all functions like `fromModelPathAndPolicyFile()` in: https://github.com/casbin/dart-casbin/blob/97a95d1468de40226776c33e66d8ae6a36002d26/lib/src/enforcer.dart

**Comment by hsluoyz** [comment]
@Rishabhmodii

/cc @MrUnfunny

**Comment by MrUnfunny** [comment]
@Rishabhmodii I think you can get started with this right away. Let me know if you need further clarifications.
