### ISSUE TITLE
Rename this project to dart_casbin or dart-casbin

### ISSUE THREAD

**Issue by hsluoyz** [casbin/dart-casbin#6]
I have been searching in the Dart packages: https://pub.dev/dart/packages?q=dart&page=2

And it seems that a more dart-style naming convention for a Dart package would be: dart_casbin or dart-casbin, but I'm not a Dart developer so I'm not so sure.

@KNawm @santhoshivan23 any opinions?

**Comment by santhoshivan23** [comment]
@hsluoyz  I agree! Although I felt simply _casbin_ is great. But it's not consistent with the conventions that are adopted for repositories under this organisation's GitHub.

**Comment by hsluoyz** [comment]
@santhoshivan23 yes. We will definitely name as casbin in the package manager: https://pub.dev/

Here I'm just looking for a name for GitHub repo and some other occasions (e.g. listed with other languages).

**Comment by KNawm** [comment]
The package name is casbin, so it'll show that in pub.dev. As for the repo, my advice would be keeping lowercase with hyphens as the style, but maybe changing it to `dart-casbin` would be more consistent with other repos under the org.

**Comment by hsluoyz** [comment]
Good points! Already changed to: https://github.com/casbin/dart-casbin
