### ISSUE TITLE
Implement Null-Safety

### ISSUE THREAD

**Issue by MrUnfunny** [casbin/dart-casbin#7]
Hello Everyone

Since Null Safety is now supported in stable version of Dart, I think we should implement it from the beginning itself. If you think we should migrate, I would like to send a PR for this.

**Comment by hsluoyz** [comment]
@KNawm

**Comment by KNawm** [comment]
Please go ahead @MrUnfunny, #5 should land soon so work with those changes.

**Comment by MrUnfunny** [comment]
Okay, I'll make changes after the new PR.
